default_mode: "impedance"

position:
  kp: [300, 300, 300, 300, 300, 80, 80]
  kd: [40, 40, 40, 40, 40, 20, 20]
  tau_max: [87, 87, 87, 87, 12, 12, 12]

impedance:
  K_cart: [1000, 1000, 1000, 50, 50, 50]
  D_cart: [100, 100, 100, 10, 10, 10]
  K_null: 10
  tau_max: [87, 87, 87, 87, 12, 12, 12]