default_mode: "position"

position:
  kp: [300, 300, 300, 300, 300, 80, 80]
  kd: [40, 40, 40, 40, 40, 20, 20]
  tau_max: [87, 87, 87, 87, 12, 12, 12]

impedance:
  K_cart: [400, 400, 400, 50, 50, 50]
  D_cart: [30, 30, 30, 10, 10, 10]
  K_null: 0
  tau_max: [87, 87, 87, 87, 12, 12, 12]