default_mode: "position"

position:
  kp: [150, 150, 150, 150, 80, 40, 40]
  kd: [10, 10, 10, 10, 5, 5, 5]
  tau_max: [87, 87, 87, 87, 12, 12, 12]

impedance:
  K_cart: [1000, 1000, 1000, 50, 50, 50]
  D_cart: [100, 100, 100, 10, 10, 10]
  K_null: 10
  tau_max: [87, 87, 87, 87, 12, 12, 12]