world_model: assets/mujoco/scenes/world_scene.xml
control_rate: 200

render_cameras:
  - name: eye_in_hand
    attachment: arm
    enabled: False
    width: 640
    height: 480
  
  - name: workspace_overview
    attachment: False
    enabled: True
    width: 640
    height: 480

display:
  # Options: horizontal, vertical, grid
  layout: grid
  grid_cols: 2
  window_name: "Robot Camera Views"

# Logging configuration
logging:
  enabled: True
  frequency: 200

video_logging:
  enabled: True
  frequency: 20
  cameras:
    - workspace_overview
    - eye_in_hand

# Add and configure devices such as robots
devices:
  - name: arm
    type: robot
    enabled: True
    model_path: assets/mujoco/robots/panda/panda_nohand_torque_eye_in_hand.xml
    urdf_path: assets/urdf/panda/panda.urdf
    urdf_ee_name: fr3_link8
    ctrl_param: configs/control/panda_arm.yaml
    dof: 7
    base_pose:
      position: [0, 0, 0.425]
      orientation: [0, 0, 0, 1]
    q0: [0.0, -0.785398, 0.0, -2.356194, 0.0, 1.570796, 0.785398, 0.04, 0.04]


# Add and configure objects such as table, box etc
objects:
  - name: table
    type: static
    model_path: assets/mujoco/props/table.xml
    pose:
      position: [0, 0, 0]
      orientation: [1, 0, 0, 0]

# Add and configure cameras such as overall viewpoint
cameras:
  - name: workspace_overview
    type: fixed
    pos: [0, -1.2, 0.8]
    quat: [0.7071, 0.7071, 0, 0]
    fovy: 60